Lista de Palestras
pythonbrasil/pycon-amazonia-memorial pull request #43
Opened 2017-11-03 09:39 UTC by Edely

Insere a lista de palestras, resolvendo #24 .

2017-11-03 13:23 UTC, jtemporal requested changes
detalhes :P

2017-11-03 13:23 UTC, jtemporal commented on source/pyconamazonia2017.rst
> +
acho q foram esquecidos esses espaços em branco, que acha de apagar eles? =)

2017-11-03 13:23 UTC, jtemporal commented on source/pyconamazonia2017.rst
> +12/08
que tal colocar uma linha embaixo da data com `^^^^^^^^^^^^^^^^^^^^^^^^` pra criar uma subsubseção?

2017-11-03 13:23 UTC, jtemporal commented on source/pyconamazonia2017.rst
> +13/08
que tal colocar uma linha embaixo da data com `^^^^^^^^^^^^^^^^^^^^^^^^` pra criar uma subsubseção?

2017-11-03 13:23 UTC, jtemporal commented on source/pyconamazonia2017.rst
> +- `Fernando Massanori <http://amazonia.python.org.br/images/slides/Fernando%20Massanori%20-%20Seja%20Feliz%20Programando%20em%20Python.pdf>`_
coloca uma linha em branco entre a 56 e a 57 pra manter o mesmo padrão das outras subseções ;)

2017-11-03 13:23 UTC, jtemporal commented on source/pyconamazonia2017.rst
> +
acho que não precisamos dessa linha aqui né?!

2017-11-07 14:41 UTC, Edely commented on source/pyconamazonia2017.rst
> +
Oi. Esse espaço fica mesmo, como nos demais tópicos (Conclusões, Keynotes, etc). O negócio é que num commit anterior eu tinha mexido nessa parte e acabei retornando para como tava nesse último commit. 

As demais coisas eu tô arrumando.

2018-01-13 13:14 UTC, jtemporal approved these changes

2018-01-13 13:14 UTC, merged

2018-01-13 13:14 UTC, jtemporal commented
Obrigada @Edely <3